#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.incremental=false

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dsun.zip.disableMemoryMapping=true
org.gradle.configuration-cache=false
org.gradle.caching=false
org.gradle.vfs.watch=false
org.gradle.workers.max=1

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.incremental.java=false